return {
    name = "multimedia",
    description = "Multimedia keys: volume, brightness, media control",

    keys = {
        {
            key = "XF86AudioRaiseVolume",
            mod = "",
            action = hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
            opts = { locked = true, repeating = true },
            desc = "Raise volume",
            category = "Multimedia",
        },
        {
            key = "XF86AudioLowerVolume",
            mod = "",
            action = hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
            opts = { locked = true, repeating = true },
            desc = "Lower volume",
            category = "Multimedia",
        },
        {
            key = "XF86AudioMute",
            mod = "",
            action = hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
            opts = { locked = true, repeating = true },
            desc = "Toggle mute",
            category = "Multimedia",
        },
        {
            key = "XF86AudioMicMute",
            mod = "",
            action = hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
            opts = { locked = true, repeating = true },
            desc = "Toggle mic mute",
            category = "Multimedia",
        },
        {
            key = "XF86MonBrightnessUp",
            mod = "",
            action = hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),
            opts = { locked = true, repeating = true },
            desc = "Brightness up",
            category = "Multimedia",
        },
        {
            key = "XF86MonBrightnessDown",
            mod = "",
            action = hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),
            opts = { locked = true, repeating = true },
            desc = "Brightness down",
            category = "Multimedia",
        },
        {
            key = "XF86AudioNext",
            mod = "",
            action = hl.dsp.exec_cmd("playerctl next"),
            opts = { locked = true },
            desc = "Next track",
            category = "Multimedia",
        },
        {
            key = "XF86AudioPause",
            mod = "",
            action = hl.dsp.exec_cmd("playerctl play-pause"),
            opts = { locked = true },
            desc = "Play/Pause",
            category = "Multimedia",
        },
        {
            key = "XF86AudioPlay",
            mod = "",
            action = hl.dsp.exec_cmd("playerctl play-pause"),
            opts = { locked = true },
            desc = "Play/Pause",
            category = "Multimedia",
        },
        {
            key = "XF86AudioPrev",
            mod = "",
            action = hl.dsp.exec_cmd("playerctl previous"),
            opts = { locked = true },
            desc = "Previous track",
            category = "Multimedia",
        },
    },
}
